# Site wide configuration

title: aadm.github.io
locale: en_US
description: "photography and personal stories by Alessandro Amato del Monte"
logo: #site-logo.png
search: true
url: http://localhost:4000

# Jekyll configuration

permalink: /:year-:month-:day-:title.html
# permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Alessandro Amato del Monte
  avatar:
  email: alessandro.adm@gmail.com
  twitter: aadmtwi
  github: aadm
  instagram: aadm
  flickr: aadm
  tumblr: aadm-fotografia
  google:
    plus: AlessandroAmatodelMonte
    analytics: 'UA-32354823-1'
    verify:
    ad-client:
    ad-slot:
  bing-verify:
